Feature/rename to termius
EvgeneOskin/termius-cli pull request #6
Opened 2016-11-18 12:50 UTC by Maxbey

2016-11-19 04:43 UTC, EvgeneOskin requested changes
Please find me notes in changes.

2016-11-19 04:43 UTC, EvgeneOskin commented on README.md
> +# Termius ssh config utility
It should be "Termius CLI"

2016-11-19 04:43 UTC, EvgeneOskin commented on README.md
> +Termius ssh config utility can be installed via [pip](http://www.pip-installer.org/en/latest/index.html):
I should be "Termius CLI"

2016-11-20 03:52 UTC, Maxbey commented
@EvgeneOskin Readme fixed.

2016-11-20 08:55 UTC, EvgeneOskin approved these changes

2016-11-20 08:55 UTC, merged